name: "ROS 2 CI Action"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    steps:
    - uses: ros-tooling/setup-ros@master
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: ros2_action_test
        target-ros2-distro: foxy

